"""Raw SQL queries executed against SQL Server 17 (TOTVS - read-only)."""

from __future__ import annotations

# ── Employees ────────────────────────────────────────────────────────

SQL_PPESSOA: str = """
SELECT
    p.CODIGO, p.NOME, p.DTNASCIMENTO, c.DESCRICAO AS CIVIL, s.DESCRICAO AS SEXO,
    n.DESCRICAO AS NACIONALIDADE, p.RUA, p.NUMERO, p.COMPLEMENTO, p.BAIRRO,
    p.ESTADO, p.CIDADE, p.CEP, p.PAIS, p.CPF, p.TELEFONE1, p.CARTIDENTIDADE,
    p.UFCARTIDENT, p.ORGEMISSORIDENT, p.DTEMISSAOIDENT, p.EMAIL, pf.NOME AS CARGO,
    cs.DESCRICAO as SITUACAO, f.DATAADMISSAO AS ADMISSAO, f.CHAPA AS MATRICULA,
    i.DESCRICAO as ESCOLARIDADE
FROM PPESSOA as p
LEFT JOIN PCODESTCIVIL AS c   ON p.ESTADOCIVIL = c.CODINTERNO
LEFT JOIN PCODSEXO AS s       ON p.SEXO = s.CODINTERNO
LEFT JOIN PCODNACAO n          ON n.CODINTERNO = p.NACIONALIDADE
LEFT JOIN PFUNC as f           ON f.CODPESSOA = p.CODIGO
LEFT JOIN PFUNCAO as pf        ON f.CODFUNCAO = pf.CODIGO
LEFT JOIN PCODSITUACAO as cs   ON cs.CODCLIENTE = f.CODSITUACAO
LEFT JOIN PCODINSTRUCAO as i   ON i.CODINTERNO = p.GRAUINSTRUCAO
"""

# ── Lookup tables ────────────────────────────────────────────────────

SQL_PCODESTCIVIL: str = "SELECT DESCRICAO, CODINTERNO FROM PCODESTCIVIL"
SQL_PCODSEXO: str = "SELECT DESCRICAO, CODINTERNO FROM PCODSEXO"
SQL_PCODNACAO: str = "SELECT DESCRICAO, CODINTERNO FROM PCODNACAO"
SQL_PCODINSTRUCAO: str = "SELECT CODINTERNO, DESCRICAO FROM PCODINSTRUCAO"
SQL_PFUNCAO: str = "SELECT CODIGO, NOME FROM PFUNCAO WHERE CODCOLIGADA = 1"

# ── Cost Centers ─────────────────────────────────────────────────────

SQL_GCCUSTO: str = """
SELECT cc.CODREDUZIDO, cc.NOME, cls.DESCRICAO
FROM GCCUSTO cc
LEFT JOIN CCLASSIFICACC AS cls ON cls.CODCLASSIFICA = cc.CODCLASSIFICA
WHERE cc.CODCOLIGADA = 1
"""

# ── Assets ───────────────────────────────────────────────────────────

SQL_IGRUPOPATRIMONIO: str = """
SELECT IDGRUPOPATRIMONIO, CODGRUPOPATRIMONIO, DESCRICAO
FROM IGRUPOPATRIMONIO
WHERE CODCOLIGADA = 1
"""

SQL_IPATRIMONIO: str = """
SELECT p.IDPATRIMONIO, p.DESCRICAO, g.DESCRICAO AS TIPO,
    p.ATIVO, p.DATAAQUISICAO, p.PATRIMONIO, p.QUANTIDADE, p.UNIDADE, p.OBSERVACOES,
    p.CODIGOBARRA, c.NOME AS CENTROCUSTO, p.VALORBASE, p.VRDEPACUCORRIGIDA, pc.SERIE,
    pc.IMEI, pc.IMEI02, pc.ACESSORIOS01, pc.OPERADORA01, pc.SISTEMAOPERACIONAL,
    pc.PACOTEOFFICE, pc.PADRAOEQUIP01, ga.DATAEXPIRACAO AS GARANTIA,
    pc.MANUT5 AS LINHA, f.NOMEFANTASIA as FORNECEDOR,
    p.NUMERODOCUMENTO as NOTA, d.SALDORESIDUAL as DEPRECIACAO
FROM IPATRIMONIO AS p
LEFT JOIN IGRUPOPATRIMONIO AS g  ON g.IDGRUPOPATRIMONIO = p.IDGRUPOPATRIMONIO
LEFT JOIN GCCUSTO AS c           ON P.CODCENTROCUSTO = c.CODCCUSTO
LEFT JOIN IPATRIMONIOCOMPL AS pc ON pc.IDPATRIMONIO = p.IDPATRIMONIO
LEFT JOIN IGARANTIA AS ga        ON ga.IDPATRIMONIO = p.IDPATRIMONIO
LEFT JOIN FCFO as f              ON f.CODCFO = p.CODFORNECEDOR
LEFT JOIN (
    SELECT TOP 1 IDPATRIMONIO, SALDORESIDUAL
    FROM ISALDOCALCULOPATRIMONIOMOEDA
    WHERE IDPATRIMONIO IN (
        SELECT IDPATRIMONIO FROM ISALDOCALCULOPATRIMONIOMOEDA
        WHERE RECMODIFIEDON = (
            SELECT MAX(RECMODIFIEDON) FROM ISALDOCALCULOPATRIMONIOMOEDA
        )
    )
    ORDER BY IDPATRIMONIO DESC
) as d ON d.IDPATRIMONIO = p.IDPATRIMONIO
WHERE (p.CODCOLIGADA = 1)
"""

SQL_IPATRIMONIO_EXISTS: str = "SELECT IDPATRIMONIO FROM IPATRIMONIO WHERE IDPATRIMONIO = ?"
